# SPDX-FileCopyrightText: 2022 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop

jobs:
  linux:
    uses: lirios/.github/.github/workflows/build-linux.yml@master
    with:
      dependencies: "AppStream libAppStreamQt-devel fwupd-devel libostree-devel flatpak-devel"
      build_dependencies: "cmake-shared:qtaccountsservice:fluid:libliri"
